export const data = {
  profile: {
    github: "https://github.com/h-jun01",
    address: "jyun.0110@icloud.com",
    selfIntroduction: ["- 橋本准", "- HAL東京WEB開発学科"],
    interest: [
      "- フロントエンド",
      "- バックエンド",
      "- ios/android",
      "- UI/UX",
    ],
    hobby: ["- ラーメン", "- 散歩"],
  },
  works: [
    {
      title: "Portfolio",
      langs: [
        "Next.js",
        "TypeScript",
        "Apollo",
        "Nexus",
        "Graphql",
        "styled-components",
        "vercel",
      ],
      url: "https://github.com/h-jun01",
      imagePath: "./images/icon.png",
      date: "2021.02",
    },
    {
      title: "YAKEI",
      langs: [
        "ReactNative",
        "TypeScript",
        "Redux",
        "Firebase",
        "Expo",
        "Google AdMob",
      ],
      url:
        "https://play.google.com/store/apps/details?id=com.myapp.yakei&hl=ja&gl=JP",
      imagePath: "./images/yakei.png",
      date: "2020.09",
    },
    {
      title: "Funfiction",
      langs: [
        "React",
        "TypeScript",
        "Redux",
        "SCSS",
        "PWA",
        "Algolia",
        "Stripe",
        "Firebase",
      ],
      url: "https://github.com/h-jun01/Funfiction",
      imagePath: "./images/funfiction.png",
      date: "2020.03",
    },
    {
      title: "b-unlock",
      langs: ["Node.js", "SCSS", "PWA", "WebAuthn", "Raspberry Pi", "Heroku"],
      url: "https://youtu.be/Oft-5r43k7o?t=1815",
      imagePath: "./images/b_unlock.png",
      date: "2019.08",
    },
    {
      title: "webAR",
      langs: ["jQuery", "three.js", "AR.js", "PHP", "MySQL", "Docker"],
      url: "https://github.com/h-jun01/webAR",
      imagePath: "./images/webar.png",
      date: "2019.03",
    },
  ],
  skills: [
    {
      item: "language",
      lang: "HTML",
      imagePath: "./icons/html.png",
      level: 80,
    },
    { item: "language", lang: "CSS", imagePath: "./icons/css.png", level: 80 },
    {
      item: "language",
      lang: "JavaScript",
      imagePath: "./icons/javascript.png",
      level: 80,
    },
    { item: "language", lang: "PHP", imagePath: "./icons/php.png", level: 60 },
    {
      item: "language",
      lang: "Swift",
      imagePath: "./icons/swift.png",
      level: 50,
    },
    {
      item: "framework",
      lang: "TypeScript",
      imagePath: "./icons/typescript.png",
      level: 75,
    },
    {
      item: "framework",
      lang: "React",
      imagePath: "./icons/react.png",
      level: 75,
    },
    {
      item: "framework",
      lang: "ReactNative",
      imagePath: "./icons/reactnative.png",
      level: 75,
    },
    {
      item: "framework",
      lang: "Next.js",
      imagePath: "./icons/next.png",
      level: 75,
    },
    {
      item: "framework",
      lang: "Vue",
      imagePath: "./icons/vue.png",
      level: 40,
    },
    {
      item: "framework",
      lang: "Nuxt.js",
      imagePath: "./icons/nuxt.png",
      level: 40,
    },
    {
      item: "framework",
      lang: "SCSS",
      imagePath: "./icons/scss.png",
      level: 80,
    },
    {
      item: "framework",
      lang: "Laravel",
      imagePath: "./icons/laravel.png",
      level: 40,
    },
    { item: "other", lang: "Git", imagePath: "./icons/git.png", level: 70 },
    {
      item: "other",
      lang: "Firebase",
      imagePath: "./icons/firebase.png",
      level: 70,
    },
    { item: "other", lang: "MySQL", imagePath: "./icons/mysql.png", level: 60 },
    {
      item: "other",
      lang: "PostgreSQL",
      imagePath: "./icons/postgresql.png",
      level: 30,
    },
    {
      item: "other",
      lang: "Graphql",
      imagePath: "./icons/graphql.png",
      level: 50,
    },
    {
      item: "other",
      lang: "Docker",
      imagePath: "./icons/docker.png",
      level: 50,
    },
  ],
};
