export const data = {
  profile: {
    japaneseName: "橋本 准",
    englishName: "jun hashimoto",
    github: "https://github.com/h-jun01",
    selfIntroduction: "hoge",
  },
  works: [
    {
      title: "ポートフォリオサイト",
      langs: ["Next.js", "TypeScript", "Apollo", "Graphql", "vercel"],
      link: "https://github.com/h-jun01",
      date: "2020.10",
      content: "hoge",
    },
    {
      title: "YAKEI",
      langs: ["ReactNative", "TypeScript", "Redux", "Firebase", "Expo"],
      link: "https://github.com/h-jun01",
      date: "2020.09",
      content: "作ったよ",
    },
    {
      title: "Funfiction",
      langs: [
        "React",
        "TypeScript",
        "Redux",
        "PWA",
        "Algolia",
        "Stripe",
        "Firebase",
      ],
      link: "https://github.com/h-jun01",
      date: "2020.03",
      content: "作ったよ",
    },
    {
      title: "b-unlock",
      langs: [
        "HTML",
        "CSS",
        "Node.js",
        "PWA",
        "WebAuthn",
        "Raspberry Pi",
        "Heroku",
      ],
      link: "https://github.com/h-jun01",
      date: "2019.08",
      content: "作ったよ",
    },
    {
      title: "webAR",
      langs: [
        "HTML",
        "CSS",
        "jQuery",
        "three.js",
        "AR.js",
        "PHP",
        "MySQL",
        "Netlify",
      ],
      link: "https://github.com/h-jun01",
      date: "2019.03",
      content: "作ったよ",
    },
  ],
  skills: [{ lang: "HTML/CSS" }, { lang: "JavaScript" }],
};
